using Hackathon.Repository.Entity;
using Hackathon.Repository.Enum;
using Microsoft.EntityFrameworkCore;

namespace Hackathon.Repository.Seed;

public static class EventSeed
{
    public static void SeedEvents(this ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Events>().HasData(
            // Draft events
            new Events { Id = SeedConstants.Event1Draft, Name = "SEAL Hackathon - Spring Draft", Description = "Spring 2026 draft event for testing", Status = EventStatusEnum.Draft, Season = SeasonEnum.Spring, StartTime = SeedConstants.CreatedAt.AddDays(10), EndTime = SeedConstants.CreatedAt.AddDays(30), RegisterLimitTime = SeedConstants.CreatedAt.AddDays(9), LimitTeam = 10, MinMember = 2, MaxMember = 4, NumberRound = 2, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Events { Id = SeedConstants.Event5Draft, Name = "SEAL Hackathon - Summer Draft", Description = "Summer 2026 draft event", Status = EventStatusEnum.Draft, Season = SeasonEnum.Summer, StartTime = SeedConstants.CreatedAt.AddDays(40), EndTime = SeedConstants.CreatedAt.AddDays(60), RegisterLimitTime = SeedConstants.CreatedAt.AddDays(38), LimitTeam = 12, MinMember = 3, MaxMember = 5, NumberRound = 2, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Events { Id = SeedConstants.Event8Draft, Name = "SEAL Hackathon - Autumn Draft", Description = "Autumn 2026 draft event", Status = EventStatusEnum.Draft, Season = SeasonEnum.Autumn, StartTime = SeedConstants.CreatedAt.AddDays(70), EndTime = SeedConstants.CreatedAt.AddDays(90), RegisterLimitTime = SeedConstants.CreatedAt.AddDays(68), LimitTeam = 10, MinMember = 2, MaxMember = 5, NumberRound = 2, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            // Published events
            new Events { Id = SeedConstants.Event2Published, Name = "SEAL Hackathon - Spring Published", Description = "Main active Spring event", Status = EventStatusEnum.Published, Season = SeasonEnum.Spring, StartTime = SeedConstants.CreatedAt.AddDays(10), EndTime = SeedConstants.CreatedAt.AddDays(30), RegisterLimitTime = SeedConstants.CreatedAt.AddDays(9), LimitTeam = 12, MinMember = 2, MaxMember = 4, NumberRound = 2, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Events { Id = SeedConstants.Event4Published, Name = "SEAL Hackathon - Summer Published", Description = "Main active Summer event", Status = EventStatusEnum.Published, Season = SeasonEnum.Summer, StartTime = SeedConstants.CreatedAt.AddDays(10), EndTime = SeedConstants.CreatedAt.AddDays(30), RegisterLimitTime = SeedConstants.CreatedAt.AddDays(9), LimitTeam = 15, MinMember = 2, MaxMember = 4, NumberRound = 2, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Events { Id = SeedConstants.Event7Published, Name = "SEAL Hackathon - Autumn Published", Description = "Main active Autumn event", Status = EventStatusEnum.Published, Season = SeasonEnum.Autumn, StartTime = SeedConstants.CreatedAt.AddDays(10), EndTime = SeedConstants.CreatedAt.AddDays(30), RegisterLimitTime = SeedConstants.CreatedAt.AddDays(9), LimitTeam = 10, MinMember = 2, MaxMember = 4, NumberRound = 2, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Events { Id = SeedConstants.Event10Published, Name = "SEAL Hackathon - Winter Published", Description = "Main active Winter event", Status = EventStatusEnum.Published, Season = SeasonEnum.Winter, StartTime = SeedConstants.CreatedAt.AddDays(10), EndTime = SeedConstants.CreatedAt.AddDays(30), RegisterLimitTime = SeedConstants.CreatedAt.AddDays(9), LimitTeam = 10, MinMember = 2, MaxMember = 4, NumberRound = 2, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            // Closed events
            new Events { Id = SeedConstants.Event3Closed, Name = "SEAL Hackathon - Spring Closed", Description = "Completed Spring event", Status = EventStatusEnum.Closed, Season = SeasonEnum.Spring, StartTime = SeedConstants.CreatedAt.AddDays(-30), EndTime = SeedConstants.CreatedAt.AddDays(-10), RegisterLimitTime = SeedConstants.CreatedAt.AddDays(-31), LimitTeam = 8, MinMember = 2, MaxMember = 5, NumberRound = 2, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Events { Id = SeedConstants.Event6Closed, Name = "SEAL Hackathon - Summer Closed", Description = "Completed Summer event", Status = EventStatusEnum.Closed, Season = SeasonEnum.Summer, StartTime = SeedConstants.CreatedAt.AddDays(-60), EndTime = SeedConstants.CreatedAt.AddDays(-40), RegisterLimitTime = SeedConstants.CreatedAt.AddDays(-61), LimitTeam = 10, MinMember = 2, MaxMember = 4, NumberRound = 2, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Events { Id = SeedConstants.Event9Closed, Name = "SEAL Hackathon - Winter Closed", Description = "Completed Winter event", Status = EventStatusEnum.Closed, Season = SeasonEnum.Winter, StartTime = SeedConstants.CreatedAt.AddDays(-90), EndTime = SeedConstants.CreatedAt.AddDays(-70), RegisterLimitTime = SeedConstants.CreatedAt.AddDays(-91), LimitTeam = 10, MinMember = 2, MaxMember = 4, NumberRound = 2, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt }
        );
    }
}
