using Hackathon.Repository.Entity;
using Hackathon.Repository.Enum;
using Microsoft.EntityFrameworkCore;

namespace Hackathon.Repository.Seed;

public static class NotificationSeed
{
    public static void SeedNotifications(this ModelBuilder modelBuilder)
    {
        // 25 Notifications
        modelBuilder.Entity<Notifications>().HasData(
            // Personal notifications
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000001"), UserId = SeedConstants.UserStudentLeader1, TeamId = null, Title = "Chào mừng bạn", Status = NotificationStatusEnum.Read, Description = "Chào mừng bạn gia nhập hệ thống SEAL Hackathon", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000002"), UserId = SeedConstants.UserStudentLeader2, TeamId = null, Title = "Xác thực email", Status = NotificationStatusEnum.Unread, Description = "Vui lòng xác thực email để kích hoạt tài khoản", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000003"), UserId = SeedConstants.UserJudgeActive, TeamId = null, Title = "Lịch chấm thi", Status = NotificationStatusEnum.Pending, Description = "Bạn được phân công chấm thi vòng 1", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000004"), UserId = SeedConstants.UserStaffActive, TeamId = null, Title = "Báo cáo mới", Status = NotificationStatusEnum.Read, Description = "Có 3 báo cáo mới từ sinh viên", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000005"), UserId = SeedConstants.UserAdminActive, TeamId = null, Title = "Thống kê hệ thống", Status = NotificationStatusEnum.Read, Description = "Có 15 đội thi đã đăng ký", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            // Team notifications
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000006"), UserId = SeedConstants.UserStudentLeader1, TeamId = TeamSeed.Team1, Title = "Đăng ký thành công", Status = NotificationStatusEnum.Read, Description = "Alpha Tech đã đăng ký thành công vào giải", TargetType = NotificationTargetTypeEnum.Team, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000007"), UserId = SeedConstants.UserStudentLeader2, TeamId = TeamSeed.Team2, Title = "Gợi ý đề tài", Status = NotificationStatusEnum.Unread, Description = "Có đề tài mới phù hợp với đội của bạn", TargetType = NotificationTargetTypeEnum.Team, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000008"), UserId = SeedConstants.UserStudentMember1, TeamId = TeamSeed.Team1, Title = "Nhắc nhở nộp bài", Status = NotificationStatusEnum.Unread, Description = "Hạn nộp bài sắp hết, vui lòng nộp trước 23:59", TargetType = NotificationTargetTypeEnum.Team, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000009"), UserId = SeedConstants.UserStudentLeader3, TeamId = TeamSeed.Team3, Title = "Cảnh báo vi phạm", Status = NotificationStatusEnum.Unread, Description = "Thành viên của bạn đã bị phát hiện vi phạm quy chế", TargetType = NotificationTargetTypeEnum.Team, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000010"), UserId = SeedConstants.UserStudentLeader4, TeamId = TeamSeed.Team4, Title = "Điểm số mới", Status = NotificationStatusEnum.Read, Description = "Điểm vòng 1 đã được công bố", TargetType = NotificationTargetTypeEnum.Team, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            // System notifications
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000011"), UserId = null, TeamId = null, Title = "Bảo trì hệ thống", Status = NotificationStatusEnum.Unread, Description = "Hệ thống sẽ bảo trì từ 22h-23h ngày mai", TargetType = NotificationTargetTypeEnum.System, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000012"), UserId = null, TeamId = null, Title = "Cập nhật quy chế", Status = NotificationStatusEnum.Unread, Description = "Quy chế giải đã được cập nhật mới", TargetType = NotificationTargetTypeEnum.System, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000013"), UserId = null, TeamId = null, Title = "Gia hạn đăng ký", Status = NotificationStatusEnum.Read, Description = "Hạn đăng ký được kéo dài thêm 3 ngày", TargetType = NotificationTargetTypeEnum.System, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            // More personal notifications
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000014"), UserId = SeedConstants.UserStudentLeader5, TeamId = null, Title = "Mentor mới", Status = NotificationStatusEnum.Unread, Description = "Bạn có mentor mới được phân công", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000015"), UserId = SeedConstants.UserStudentLeader6, TeamId = null, Title = "Kết quả vòng 2", Status = NotificationStatusEnum.Pending, Description = "Kết quả vòng 2 sắp được công bố", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000016"), UserId = SeedConstants.UserStudentLeader7, TeamId = null, Title = "Giải thưởng", Status = NotificationStatusEnum.Unread, Description = "Đội của bạn đã đạt giải nhất chung cuộc", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000017"), UserId = SeedConstants.UserStudentLeader1, TeamId = null, Title = "Tài khoản bị khóa", Status = NotificationStatusEnum.Read, Description = "Tài khoản của bạn tạm thời bị khóa do đăng nhập sai nhiều lần", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000018"), UserId = SeedConstants.UserStudentInactive, TeamId = null, Title = "Nhắc nhở xác thực", Status = NotificationStatusEnum.Pending, Description = "Vui lòng xác thực email để tiếp tục sử dụng", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000019"), UserId = SeedConstants.UserStudentBanned, TeamId = null, Title = "Tài khoản bị cấm", Status = NotificationStatusEnum.Read, Description = "Tài khoản bị cấm vĩnh viễn do gian lận", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            // More team notifications
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000020"), UserId = SeedConstants.UserStudentLeader3, TeamId = TeamSeed.Team3, Title = "Thành viên rời đội", Status = NotificationStatusEnum.Read, Description = "Thành viên đã rời khỏi đội của bạn", TargetType = NotificationTargetTypeEnum.Team, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000021"), UserId = SeedConstants.UserStudentMember5, TeamId = TeamSeed.Team5, Title = "Mời vào đội", Status = NotificationStatusEnum.Pending, Description = "Bạn được mời vào đội Epsilon AI", TargetType = NotificationTargetTypeEnum.Team, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            // Disabled notifications
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000022"), UserId = SeedConstants.UserStudentLeader1, TeamId = null, Title = "Thông báo cũ", Status = NotificationStatusEnum.Read, Description = "Thông báo đã bị vô hiệu hóa", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = true, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000023"), UserId = null, TeamId = null, Title = "Hệ thống cũ", Status = NotificationStatusEnum.Read, Description = "Thông báo hệ thống cũ đã bị vô hiệu", TargetType = NotificationTargetTypeEnum.System, IsDisable = true, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            // More personal
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000024"), UserId = SeedConstants.UserMentorActive, TeamId = null, Title = "Phân công đội", Status = NotificationStatusEnum.Unread, Description = "Bạn được phân công hướng dẫn đội mới", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new Notifications { Id = Guid.Parse("90000000-0000-0000-0000-000000000025"), UserId = SeedConstants.UserStudentMember10, TeamId = null, Title = "Xác nhận tham gia", Status = NotificationStatusEnum.Read, Description = "Bạn đã được xác nhận tham gia giải", TargetType = NotificationTargetTypeEnum.Personal, IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt }
        );

        // 15 Mentor Notifications
        modelBuilder.Entity<MentorNotifications>().HasData(
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000001"), AssignTrackId = AssignmentSeed.At11, Title = "Yêu cầu mentor AI", Description = "Sinh viên cần hướng dẫn về AI", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000002"), AssignTrackId = AssignmentSeed.At11, Title = "Kiểm tra tiến độ", Description = "Nhắc nhở kiểm tra tiến độ đội", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000003"), AssignTrackId = AssignmentSeed.At12, Title = "Yêu cầu mentor Security", Description = "Hỗ trợ về bảo mật hệ thống", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000004"), AssignTrackId = AssignmentSeed.At12, Title = "Đánh giá bảo mật", Description = "Xem xét code của đội", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000005"), AssignTrackId = AssignmentSeed.At13, Title = "Yêu cầu mentor AI E7", Description = "Cần tư vấn về model AI", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000006"), AssignTrackId = AssignmentSeed.At13, Title = "Demo sản phẩm", Description = "Đội đã sẵn sàng demo", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000007"), AssignTrackId = AssignmentSeed.At14, Title = "Hỗ trợ deploy", Description = "Cần giúp deploy lên cloud", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000008"), AssignTrackId = AssignmentSeed.At15, Title = "Yêu cầu mentor AI legacy", Description = "Hỗ trợ dự án cũ", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000009"), AssignTrackId = AssignmentSeed.At16, Title = "Yêu cầu mentor Web", Description = "Tư vấn về kiến trúc web", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000010"), AssignTrackId = AssignmentSeed.At17, Title = "Hỗ trợ blockchain", Description = "Cần giúp về smart contract", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000011"), AssignTrackId = AssignmentSeed.At11, Title = "Nháp 1", Description = "Thông báo nháp", IsDisable = true, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000012"), AssignTrackId = AssignmentSeed.At12, Title = "Nháp 2", Description = "Thông báo nháp", IsDisable = true, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000013"), AssignTrackId = AssignmentSeed.At13, Title = "Nháp 3", Description = "Thông báo nháp", IsDisable = true, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000014"), AssignTrackId = AssignmentSeed.At11, Title = "Feedback yêu cầu", Description = "Phản hồi từ sinh viên", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt },
            new MentorNotifications { Id = Guid.Parse("92000000-0000-0000-0000-000000000015"), AssignTrackId = AssignmentSeed.At13, Title = "Tài liệu mới", Description = "Có tài liệu hướng dẫn mới", IsDisable = false, CreatedAt = SeedConstants.CreatedAt, UpdatedAt = SeedConstants.CreatedAt }
        );
    }
}
